forwards:
- source: hrd099
  dest: [dyahtestgroup, refferal_link_submit_group, unlimited_referrals0, BitcoinUSA_1,
    Share_Airdrop_Link, AirdropReferralsGroup, Crypto_plus_1, airdroproviderchat,
    Link_Share_75, sharelinkairdroup, bitraderairdrop]
  offset: 0
  end: null
show_forwarded_from: false
live: {delete_sync: false, delete_on_edit: null}
past: {delay: 100.0}
admins: []
plugins: {}
